#
# Created by JFormDesigner on Sat Feb 22 14:35:54 CST 2020
#

JIpicoReaderPanel.this.border=Foxberry Reader
JIpicoReaderPanel.label1.text=Dirección IP
JIpicoReaderPanel.readerAddressTextField.text=10.19.1.101
JIpicoReaderPanel.connectButton.text=Conectar
JIpicoReaderPanel.setTimeButton.text=Fijar Hora
JIpicoReaderPanel.label2.text=Punto
JIpicoReaderPanel.label4.text=Terminal
JIpicoReaderPanel.label3.text=RX 2 (Der.)
JIpicoReaderPanel.applyCheckpointButton.text=Aplicar
JIpicoReaderPanel.label5.text=Lecturas
JIpicoReaderPanel.tagsReadLabel.text=0
JImportBackupDialog.label1.text=Archivo\:
JImportBackupDialog.openFileButton.text=Seleccionar
JImportBackupDialog.importButton.text=Importar
JImportBackupDialog.this.title=Importar respaldo
JImportBackupPanel.applyCheckPointButton.text=Aplicar punto
JImportBackupPanel.fileOpenButton.text=Abrir archivo
JImportBackupPanel.importButton.text=Importar
JImportBackupPanel.label1.text=Archivo
JImportBackupsFrame.this.title=Importar respaldos
