#
# Created by JFormDesigner on Sat Feb 22 14:35:54 CST 2020
#

JIpicoReaderPanel.this.border=TiempoMeta Cloud
JIpicoReaderPanel.label1.text=Api Key
JIpicoReaderPanel.eventTitleLabel.text=--
JIpicoReaderPanel.connectButton.text=Conectar
JIpicoReaderPanel.label2.text=Ultima solicitud
JIpicoReaderPanel.lastRequestLabel.text=--
JIpicoReaderPanel.label3.text=Última descarga
JIpicoReaderPanel.lastDownloadLabel.text=--
JIpicoReaderPanel.rewindTagReadsButton.text=Rebobinar lecturas
JIpicoReaderPanel.label5.text=Lecturas descargadas
JIpicoReaderPanel.tagsReadLabel.text=0
JIpicoReaderPanel.clearTagReadsButton.text=Borrar lecturas
